### ISSUE TITLE
Verbose per-epoch reporting

### ISSUE THREAD

**Issue by alexbw** [aigamedev/scikit-neuralnetwork#102]
Apologies for the spam of issues, just diving into the project, which I'm really liking, and asking questions here. If there's an IRC channel or mailing list that's a better place, please let me know.

I'm coming from the Torch world, where we tend to write our own training loops, and thus I'm accustomed to a lot of verbosity during training, so I can diagnose problems early. It seems that verbose=True just turns the logging level up, so that I see warnings, but I don't see any per-epoch training information. Is there a functionality for something like this in this package?

**Comment by alexjc** [comment]
Hi, this is fine for posting requests like this. There's not yet an IRC channel :-)

First, I should note that this package aims at a higher level than Torch and we're trying to provide solutions that work well with less expertize.  The underlying libraries that we wrap would be similar to Torch, e.g. Theano/pylearn or blocks.

The plan is to setup per epoch callbacks so you can do what you want in those callbacks. However, since we try to abstract away the complexity of the model/training algorithms, it might not be as straightforward to extract the data you need.

What were the things you had in mind, if you don't mind sharing the specifics?  Example output from your Torch code would be great!

**Comment by alexjc** [comment]
Close by #133.
