### ISSUE TITLE
pylearn2 has gone. but example is using pyleanr2

### ISSUE THREAD

**Issue by laesunk** [aigamedev/scikit-neuralnetwork#146]
as i know pylearn2 has gone. 

but examle source is using pylearn2 

is that right?

**Comment by alexjc** [comment]
Can you point to the specific problems when reporting bugs? A link is fine.

Fix is welcome as PR!

**Comment by laesunk** [comment]
the issue is 

"python examples/plot_mlp.py --params activation" drawing the result of each activation function.

but if someone setup without pylearn2 in master branch, error will happen

**Comment by alexjc** [comment]
Thanks, confirmed. PR welcome!

**Comment by fayeshine** [comment]
The problem is that, if we use lasagne as backend, it gives this bug:

Visualizing Parameters in a Modern Neural Network
=================================================

Traceback (most recent call last):
  File "plot_mlp.py", line 69, in <module>
    layers=[mlp.Layer(activation, units=units, **params), mlp.Layer(output)], random_state=1,
  File "/home/wenjian/anaconda2/lib/python2.7/site-packages/sknn/nn.py", line 93, in __init__
    raise NotImplementedError("Layer type `%s` is not implemented." % type)

**Comment by alexjc** [comment]
Just remove the `Maxout` activation?

**Comment by fayeshine** [comment]
#156
