### ISSUE TITLE
Issue with loading data from Pandas DataFrame

### ISSUE THREAD

**Issue by samsinai** [aigamedev/scikit-neuralnetwork#176]
I assumed the input data is basically what works for scikit-learn. I'm trying to use the MLP to learn on a (1650,94)-shaped matrix. However, I am getting an "index out of bounds error". Any ideas as to what needs to be done in preprocessing to resolve this?
I have posted it on stackoverflow: 
http://stackoverflow.com/questions/35304681/scikit-neural-network-has-trouble-with-input-data

**Comment by alexjc** [comment]
Ah, it's a Pandas data-frame and we haven't tested this yet—and apparently it doesn't work.

Can you convert to a `numpy.array` in the meantime? I haven't used Pandas yet so any help you may have on how to handle a dataframe compared to scipy sparse matrix is welcome.

**Comment by alexjc** [comment]
This one's going to take a bit of time... Not sure how to quickly index data from a PandasFrame or if this should be avoided for performance. When PandasFrame is used it's likely there'll be a lot of data.

In your case, the data is small anyway; why not convert to `numpy.array` using `.as_matrix()`?

**Comment by samsinai** [comment]
Thanks for the help, yes, I wasn't aware about the panda support.  I did that, but now I seem to have problems with the network not converging 

   raise RuntimeError("Training diverged and returned NaN.")
RuntimeError: Training diverged and returned NaN.

Any ideas why this may come up?

**Comment by alexjc** [comment]
The error message gives you suggestion, drop the learning rate by 10x. Or try another learning rule!

**Comment by cpoptic** [comment]
@alexjc Has support for Pandas DataFrames been officially added?  I'm building a NN with Sknn and keep getting an error "ValueError: could not convert string to float: <some string name here>".  I suspect it's because SKnn is expecting a NumPy array rather than a DataFrame, which has columns of different data types.

I have Theano, Keras, and Lasagne installed as well.
`pip show scikit-neuralnetwork`
Version: 0.7
`pip show Theano`
Version: 0.8.2
`pip show Keras`
Version: 1.1.1
`pip show Lasagne`
Version: 0.1
